# Generated by Django 4.2.25 on 2025-12-04 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='categoria',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PaginaWeb.proveedor'),
        ),
    ]
