# Generated by Django 4.2.25 on 2025-12-05 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0002_remove_movimiento_categoria_movimiento_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PaginaWeb.producto'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PaginaWeb.producto'),
        ),
    ]
