# Generated by Django 4.2.25 on 2025-12-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0003_alter_alerta_producto_alter_movimiento_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('patente', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
