# Generated by Django 4.2.25 on 2025-12-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0004_transportista'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
